# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oyinXO1.2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    list = []
    win = ""
    #1.0.0 // X-O chiqarish ✅
    #1.1.0 // X-O ni ko'p yozilmasligi [xatolik tuzatildi] ✅
    #1.2.0 // G'olib va Durrang ni chiqarish ✅
    #1.3.0 // Update buttonini qoshish ✅
    #1.4.0 // O'yin view labelini qoshish ✅
    #1.5.0 // harakat bu o'yin kimni galini ko'rsatishligi ✅

    #------------------------------------
    def Golib(self):
        if(self.win == "1"):
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.Oyna.setText("G'olib - 'X'")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.Oyna.setText("G'olib - 'O'")

    def Durrang(self):
        if(len(self.list) == 9):
            self.Oyna.setText("Durrang")

    def OynaniTozalash(self):
        if(self.Oyna.text() == "Yangilandi"):
            self.Oyna.clear()

    def XOuchun(self):
        if(self.Oyna.text() == "G'olib - 'X'" or self.Oyna.text() == "G'olib - 'O'" or self.Oyna.text() == "Durrang"):
            self.kimniGaliX.setText("X")
            self.kimniGaliO.setText("O")
        else:
            if(len(self.list) == 0 or
                len(self.list) == 2 or
                len(self.list) == 4 or
                len(self.list) == 6 or
                len(self.list) == 8):
                self.kimniGaliX.setText("=> X?")
                self.kimniGaliO.setText("O")
            else:
                self.kimniGaliX.setText("X")
                self.kimniGaliO.setText("=> O?")


    #---------------------------------
            

    def Birinchi(self):
        self.OynaniTozalash()
        if(self.pushButton.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton.setText("O")

        if(self.pushButton.text() == self.pushButton_2.text() and self.pushButton.text() == self.pushButton_3.text() and self.pushButton_2.text() == self.pushButton_3.text()):
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton.text() == self.pushButton_4.text() and self.pushButton.text() == self.pushButton_7.text() and self.pushButton_4.text() == self.pushButton_7.text()):
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton.text() == self.pushButton_5.text() and self.pushButton.text() == self.pushButton_9.text() and self.pushButton_5.text() == self.pushButton_9.text()):
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.win = "1"
        
        self.Durrang()
        self.Golib()
        self.XOuchun()
        
        
        
        

    def Ikkinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_2.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_2.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_2.setText("O")

        if(self.pushButton_2.text() == self.pushButton.text() and self.pushButton_2.text() == self.pushButton_3.text() and self.pushButton.text() == self.pushButton_3.text()):
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton_2.text() == self.pushButton_5.text() and self.pushButton_2.text() == self.pushButton_8.text() and self.pushButton_5.text() == self.pushButton_8.text()):
            self.pushButton.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()


    def Uchinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_3.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_3.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_3.setText("O")
        
        if(self.pushButton_3.text() == self.pushButton.text() and self.pushButton_3.text() == self.pushButton_2.text() and self.pushButton.text() == self.pushButton_2.text()):
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton_3.text() == self.pushButton_6.text() and self.pushButton_3.text() == self.pushButton_9.text() and self.pushButton_6.text() == self.pushButton_9.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.win = "1"
        elif(self.pushButton_3.text() == self.pushButton_5.text() and self.pushButton_3.text() == self.pushButton_7.text() and self.pushButton_5.text() == self.pushButton_7.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()



    def Tortinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_4.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_4.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_4.setText("O")
            
        if(self.pushButton_4.text() == self.pushButton.text() and self.pushButton_4.text() == self.pushButton_7.text() and self.pushButton.text() == self.pushButton_7.text()):
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton_4.text() == self.pushButton_5.text() and self.pushButton_4.text() == self.pushButton_6.text() and self.pushButton_5.text() and self.pushButton_6.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()
            


    def Beshinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_5.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_5.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_5.setText("O")

        if(self.pushButton_5.text() == self.pushButton.text() and self.pushButton_5.text() == self.pushButton_9.text() and self.pushButton.text() == self.pushButton_9.text()):
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.win = "1"
        elif(self.pushButton_5.text() == self.pushButton_3.text() and self.pushButton_5.text() == self.pushButton_7.text() and self.pushButton_3.text() == self.pushButton_7.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton_5.text() == self.pushButton_2.text() and self.pushButton_5.text() == self.pushButton_8.text() and self.pushButton_2.text() == self.pushButton_8.text()):
            self.pushButton.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton_5.text() == self.pushButton_4.text() and self.pushButton_5.text() == self.pushButton_6.text() and self.pushButton_4.text() and self.pushButton_6.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()
            



    def Oltinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_6.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_6.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_6.setText("O")

        if(self.pushButton_6.text() == self.pushButton_3.text() and self.pushButton_6.text() == self.pushButton_9.text() and self.pushButton_3.text() == self.pushButton_9.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.win = "1"
        elif(self.pushButton_6.text() == self.pushButton_4.text() and self.pushButton_6.text() == self.pushButton_5.text() and self.pushButton_4.text() == self.pushButton_5.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()



    def Yettinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_7.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_7.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_7.setText("O")

        if(self.pushButton_7.text() == self.pushButton.text() and self.pushButton_7.text() == self.pushButton_4.text() and self.pushButton.text() == self.pushButton_4.text()):
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"
        elif(self.pushButton_7.text() == self.pushButton_8.text() and self.pushButton_7.text() == self.pushButton_9.text() and self.pushButton_8.text() == self.pushButton_9.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.win = "1"
        elif(self.pushButton_7.text() == self.pushButton_3.text() and self.pushButton_7.text() == self.pushButton_5.text() and self.pushButton_3.text() == self.pushButton_5.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")  
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_8.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()
            
            


    def Sakkizinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_8.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_8.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_8.setText("O")
        
        if(self.pushButton_8.text() == self.pushButton_7.text() and self.pushButton_8.text() == self.pushButton_9.text() and self.pushButton_7.text() == self.pushButton_9.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.win = "1"
        elif(self.pushButton_8.text() == self.pushButton_2.text() and self.pushButton_8.text() == self.pushButton_5.text() and self.pushButton_2.text() == self.pushButton_5.text()):
            self.pushButton.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_9.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()
        

    def Toqqizinchi(self):
        self.OynaniTozalash()
        if(self.pushButton_9.text() == ""):
            self.list.append("1")
            if(len(self.list)==1 or 
                len(self.list)==3 or 
                len(self.list)==5 or 
                len(self.list)==7 or 
                len(self.list)==9):
                self.pushButton_9.setText("X")
            elif(len(self.list)==2 or 
                len(self.list)==4 or 
                len(self.list)==6 or 
                len(self.list)==8):
                self.pushButton_9.setText("O")
        
        if(self.pushButton_9.text() == self.pushButton.text() and self.pushButton_9.text() == self.pushButton_5.text() and self.pushButton.text() == self.pushButton_5.text()):
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_6.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.win = "1"
        elif(self.pushButton_9.text() == self.pushButton_3.text() and self.pushButton_9.text() == self.pushButton_6.text() and self.pushButton_3.text() == self.pushButton_6.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_7.setText("*")
            self.pushButton_8.setText("*")
            self.win = "1"
        elif(self.pushButton_9.text() == self.pushButton_8.text() and self.pushButton_9.text() == self.pushButton_7.text() and self.pushButton_8.text() == self.pushButton_7.text()):
            self.pushButton.setText("*")
            self.pushButton_2.setText("*")
            self.pushButton_3.setText("*")
            self.pushButton_4.setText("*")
            self.pushButton_5.setText("*")
            self.pushButton_6.setText("*")
            self.win = "1"

        self.Durrang()
        self.Golib()
        self.XOuchun()

    def Yangilash(self):
        if(self.Oyna.text() == "G'olib - 'X'" or self.Oyna.text() == "G'olib - 'O'" or self.Oyna.text() == "Durrang"):
            self.list = []
            self.win = ""
            self.pushButton.setText("")
            self.pushButton_2.setText("")
            self.pushButton_3.setText("")
            self.pushButton_4.setText("")
            self.pushButton_5.setText("")
            self.pushButton_6.setText("")
            self.pushButton_7.setText("")
            self.pushButton_8.setText("")
            self.pushButton_9.setText("")
            self.Oyna.clear()
            self.Oyna.setText("Yangilandi")
            self.kimniGaliX.setText("=> X?")
            self.kimniGaliO.setText("O")

    


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 70, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Birinchi)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 70, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Ikkinchi)


        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 70, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Uchinchi)


        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 150, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.Tortinchi)


        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 150, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.Beshinchi)



        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 150, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.Oltinchi)


        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 230, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.Yettinchi)


        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 230, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.Sakkizinchi)


        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 230, 91, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.Toqqizinchi)


        self.Oyna = QtWidgets.QLabel(self.centralwidget)
        self.Oyna.setGeometry(QtCore.QRect(235, 320, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.Oyna.setFont(font)
        self.Oyna.setText("")
        self.Oyna.setObjectName("Oyna")

        self.yangilash = QtWidgets.QPushButton(self.centralwidget)
        self.yangilash.setGeometry(QtCore.QRect(440, 260, 51, 51))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        self.yangilash.setFont(font)
        self.yangilash.setText("🔄")
        self.yangilash.setObjectName("yangilash")
        self.yangilash.clicked.connect(self.Yangilash)

        self.view = QtWidgets.QLabel(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(180, 20, 230, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.view.setFont(font)
        self.view.setText("X - o'yinni boshlaydi")
        self.view.setObjectName("view")

        self.kimniGaliX = QtWidgets.QLabel(self.centralwidget)
        self.kimniGaliX.setGeometry(QtCore.QRect(450, 160, 230, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.kimniGaliX.setFont(font)
        self.kimniGaliX.setText("=> X?")
        self.kimniGaliX.setObjectName("kimniGaliX")

        self.kimniGaliO = QtWidgets.QLabel(self.centralwidget)
        self.kimniGaliO.setGeometry(QtCore.QRect(450, 190, 230, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.kimniGaliO.setFont(font)
        self.kimniGaliO.setText("O")
        self.kimniGaliO.setObjectName("kimniGaliO")
        

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
